# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

multi-ecosystem-groups:
  infrastructure:
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "docker"
    directory: "/src/main/docker"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
    ignore:
      - dependency-name: "eclipse-temurin"
        versions: ["<21.0.0", ">=22.0.0"]
      - dependency-name: "eclipse-temurin:21-jre-alpine-3.22"
        # Ignore the unpinned convenience tag suggestion; keep pinning to specific build tokens instead
        versions: ["21-jre-alpine-3.22"]

  - package-ecosystem: "maven"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "infrastructure"
    ignore:
      - dependency-name: "io.quarkus:*"
        versions: [">=3.28.0"]
      - dependency-name: "io.quarkus.platform:*"
        versions: [">=3.28.0"]
      - dependency-name: "io.vertx:*"
        versions: [">=5.0.0"]
