services:
  aimathtutor:
    image: gregordietrich/aimathtutor:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    environment:
      quarkus.datasource.jdbc.url: jdbc:mariadb://mariadb:3306/aimathtutor
    ports:
      - "80:9069"
    volumes:
      - aimathtutor_logs:/deployments/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://aimathtutor:9069/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:12.0.2-noble
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: changeit
      MYSQL_DATABASE: aimathtutor
      MYSQL_USER: aimathtutor
      MYSQL_PASSWORD: changeit
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/main/resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u aimathtutor -pchangeit || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  phpmyadmin:
    image: phpmyadmin:5.2.3-apache
    restart: unless-stopped
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306

      PMA_USER: aimathtutor
      PMA_PASSWORD: changeit
    ports:
      - "42069:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://phpmyadmin/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  aimathtutor_logs:
  mariadb_data:
