services:
  aimathtutor:
    image: aimathtutor:1.0.0-SNAPSHOT
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: unless-stopped
    ports:
      - "80:9069"
    volumes:
      - ./logs/aimathtutor:/deployments/logs
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://aimathtutor:9069/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s
