package de.vptr.aimathtutor.service.ai.provider;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import de.vptr.aimathtutor.dto.AiFeedbackDto;
import de.vptr.aimathtutor.dto.ConversationContextDto;
import de.vptr.aimathtutor.dto.GraspableEventDto;
import de.vptr.aimathtutor.service.GeminiService;
import de.vptr.aimathtutor.service.ai.JsonRepairService;
import de.vptr.aimathtutor.service.ai.PromptBuilderService;
import io.quarkus.test.InjectMock;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;

@QuarkusTest
@SuppressWarnings("PMD.TooManyStaticImports")
class GeminiAiProviderTest {

    @Inject
    GeminiAiProvider geminiAiProvider;

    @InjectMock
    GeminiService geminiService;

    @InjectMock
    JsonRepairService jsonRepairService;

    @InjectMock
    PromptBuilderService promptBuilderService;

    @Test
    @DisplayName("isAvailable returns true when geminiService is configured")
    void testIsAvailable_whenConfigured() {
        when(this.geminiService.isConfigured()).thenReturn(true);
        assertTrue(this.geminiAiProvider.isAvailable());
    }

    @Test
    @DisplayName("isAvailable returns false when geminiService is not configured")
    void testIsAvailable_whenNotConfigured() {
        when(this.geminiService.isConfigured()).thenReturn(false);
        assertFalse(this.geminiAiProvider.isAvailable());
    }

    @Test
    @DisplayName("analyzeMathAction returns parsed feedback from service chain")
    void testAnalyzeMathAction_returnsParsedFeedback() {
        final var event = new GraspableEventDto();
        event.eventType = "simplify";
        final var context = new ConversationContextDto();
        final var expected = AiFeedbackDto.positive("Good job!");

        when(this.promptBuilderService.buildMathTutoringPrompt(any(), any())).thenReturn("prompt");
        when(this.geminiService.generateContent("prompt")).thenReturn("{\"type\":\"POSITIVE\"}");
        when(this.jsonRepairService.parseFeedbackFromJson(any())).thenReturn(expected);

        final var result = this.geminiAiProvider.analyzeMathAction(event, context);

        assertNotNull(result);
        assertEquals("Good job!", result.message);
    }

    @Test
    @DisplayName("answerQuestion returns content generated by geminiService")
    void testAnswerQuestion_returnsGeneratedContent() {
        final var context = new ConversationContextDto();

        when(this.promptBuilderService.buildQuestionAnsweringPrompt(any(), any(), any(), any(), any()))
                .thenReturn("q-prompt");
        when(this.geminiService.generateContent("q-prompt")).thenReturn("The answer is 42.");

        final var result = this.geminiAiProvider.answerQuestion("What is x?", "x", "x+1", "2", context);

        assertNotNull(result);
        assertEquals("The answer is 42.", result);
    }
}
