package de.vptr.aimathtutor.service.ai.provider;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import de.vptr.aimathtutor.dto.AiFeedbackDto;
import de.vptr.aimathtutor.dto.ConversationContextDto;
import de.vptr.aimathtutor.dto.GraspableEventDto;
import de.vptr.aimathtutor.service.ai.JsonRepairService;
import de.vptr.aimathtutor.service.ai.OllamaService;
import de.vptr.aimathtutor.service.ai.PromptBuilderService;
import io.quarkus.test.InjectMock;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;

@QuarkusTest
@SuppressWarnings("NullAway")
class OllamaProviderTest {

    @Inject
    OllamaProvider ollamaAiProvider;

    @InjectMock
    OllamaService ollamaService;

    @InjectMock
    JsonRepairService jsonRepairService;

    @InjectMock
    PromptBuilderService promptBuilderService;

    @Test
    @DisplayName("isAvailable returns true when ollamaService is available")
    void testIsAvailable_whenAvailable() {
        when(this.ollamaService.isAvailable()).thenReturn(true);
        assertTrue(this.ollamaAiProvider.isAvailable());
        verify(this.ollamaService).isAvailable();
    }

    @Test
    @DisplayName("isAvailable returns false when ollamaService is not available")
    void testIsAvailable_whenNotAvailable() {
        when(this.ollamaService.isAvailable()).thenReturn(false);
        assertFalse(this.ollamaAiProvider.isAvailable());
        verify(this.ollamaService).isAvailable();
    }

    @Test
    @DisplayName("analyzeMathAction returns parsed feedback from service chain")
    void testAnalyzeMathAction_returnsParsedFeedback() {
        final var event = new GraspableEventDto();
        event.eventType = "factor";
        final var context = new ConversationContextDto();
        final var expected = AiFeedbackDto.hint("Factor out the common term.");

        when(this.promptBuilderService.buildMathTutoringPrompt(event, context)).thenReturn("prompt");
        when(this.ollamaService.generateContent("prompt")).thenReturn("{\"type\":\"HINT\"}");
        when(this.jsonRepairService.parseFeedbackFromJson("{\"type\":\"HINT\"}")).thenReturn(expected);

        final var result = this.ollamaAiProvider.analyzeMathAction(event, context);

        assertNotNull(result);
        assertEquals("Factor out the common term.", result.message);
        verify(this.promptBuilderService).buildMathTutoringPrompt(event, context);
        verify(this.ollamaService).generateContent("prompt");
        verify(this.jsonRepairService).parseFeedbackFromJson("{\"type\":\"HINT\"}");
    }

    @Test
    @DisplayName("answerQuestion returns content generated by ollamaService")
    void testAnswerQuestion_returnsGeneratedContent() {
        final var context = new ConversationContextDto();

        when(this.promptBuilderService.buildQuestionAnsweringPrompt("How do I factor?", "x^2", "x^2+x", "x", context))
                .thenReturn("q-prompt");
        when(this.ollamaService.generateContent("q-prompt")).thenReturn("Factor using FOIL.");

        final var result = this.ollamaAiProvider.answerQuestion("How do I factor?", "x^2", "x^2+x", "x", context);

        assertNotNull(result);
        assertEquals("Factor using FOIL.", result);
        verify(this.promptBuilderService).buildQuestionAnsweringPrompt("How do I factor?", "x^2", "x^2+x", "x",
                context);
        verify(this.ollamaService).generateContent("q-prompt");
    }
}
