package de.vptr.aimathtutor.service.ai.provider;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import de.vptr.aimathtutor.dto.AiFeedbackDto;
import de.vptr.aimathtutor.dto.ConversationContextDto;
import de.vptr.aimathtutor.dto.GraspableEventDto;
import de.vptr.aimathtutor.service.OpenAiService;
import de.vptr.aimathtutor.service.ai.JsonRepairService;
import de.vptr.aimathtutor.service.ai.PromptBuilderService;
import io.quarkus.test.InjectMock;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;

@QuarkusTest
@SuppressWarnings("PMD.TooManyStaticImports")
class OpenAiProviderTest {

    @Inject
    OpenAiProvider openAiProvider;

    @InjectMock
    OpenAiService openAiService;

    @InjectMock
    JsonRepairService jsonRepairService;

    @InjectMock
    PromptBuilderService promptBuilderService;

    @Test
    @DisplayName("isAvailable returns true when openAiService is configured")
    void testIsAvailable_whenConfigured() {
        when(this.openAiService.isConfigured()).thenReturn(true);
        assertTrue(this.openAiProvider.isAvailable());
    }

    @Test
    @DisplayName("isAvailable returns false when openAiService is not configured")
    void testIsAvailable_whenNotConfigured() {
        when(this.openAiService.isConfigured()).thenReturn(false);
        assertFalse(this.openAiProvider.isAvailable());
    }

    @Test
    @DisplayName("analyzeMathAction returns parsed feedback via JSON mode")
    void testAnalyzeMathAction_returnsParsedFeedback() {
        final var event = new GraspableEventDto();
        event.eventType = "expand";
        final var context = new ConversationContextDto();
        final var expected = AiFeedbackDto.corrective("Try again!");

        when(this.promptBuilderService.buildMathTutoringPrompt(any(), any())).thenReturn("prompt");
        when(this.openAiService.generateJsonContent("prompt")).thenReturn("{\"type\":\"CORRECTIVE\"}");
        when(this.jsonRepairService.parseFeedbackFromJson(any())).thenReturn(expected);

        final var result = this.openAiProvider.analyzeMathAction(event, context);

        assertNotNull(result);
        assertEquals("Try again!", result.message);
    }

    @Test
    @DisplayName("answerQuestion returns content generated by openAiService")
    void testAnswerQuestion_returnsGeneratedContent() {
        final var context = new ConversationContextDto();

        when(this.promptBuilderService.buildQuestionAnsweringPrompt(any(), any(), any(), any(), any()))
                .thenReturn("q-prompt");
        when(this.openAiService.generateContent("q-prompt")).thenReturn("42 is the answer.");

        final var result = this.openAiProvider.answerQuestion("What is x?", "x", "2x", "2", context);

        assertNotNull(result);
        assertEquals("42 is the answer.", result);
    }
}
