# GitHub Actions workflow for CI/CD
# - test
# - security (SAST, secret detection, dependency scanning)
# - build
# - publish

name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run tests
        run: ./mvnw test

  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SAST (CodeQL)
        uses: github/codeql-action/init@v4
        with:
          languages: java
      - name: Build with Maven (for CodeQL)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Compile project
        run: ./mvnw clean install package -DskipTests
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
      - name: Secret Scanning
        uses: gitleaks/gitleaks-action@v2
      - name: Dependency Scanning
        uses: actions/checkout@v4
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        with:
          project: 'aimathtutor'
          path: '.'
          format: 'HTML'

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: ./mvnw clean install package -DskipTests -Pproduction

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Publish Artifacts
  #       run: echo "Add publish/deploy steps here (e.g., Docker, GitHub Packages, etc.)"
